### ISSUE TITLE
Drivers on shape keys disappear!

### ISSUE THREAD

**Issue by AwkwardFerret** [przemir/ApplyModifierForObjectWithShapeKeys#19]
Incredibly useful addon! Though much to my dismay I found that all the drivers on my shape keys disappear if I ever use it. Would it be a possibility to fix this?

**Comment by przemir** [comment]
Sorry for late response. The problem with drivers is I don't see a reliable way to transfer animation data block for shape keys from one object to another. There is a method to copy driver by script (bpy.ops.anim.copy_driver_button) but it won't work because it requires mouse position (or focus) to identify value widget.
There is a warning if object contains drivers or keyframes.

**Comment by AwkwardFerret** [comment]
Darn! Really sucks it's not possible. Appreciate the response!
