### ISSUE TITLE
Does not keep drivers

### ISSUE THREAD

**Issue by DonWippo** [przemir/ApplyModifierForObjectWithShapeKeys#7]
Hello, 
first thank you for creating this addon. 

I have a headmesh at work (can't share) that uses a Mirror Modifier and drivers for its shape keys.
When I use the function it applies the modifier and keeps the shapekeys, but not the drivers.
The drivers are essential for my purpose. 

My current workaround for this is:
1. Copy Mesh
2. Delete all Shape keys of copy
3. Apply Mirror Modifier
4. Delete original half of the copy, keep the other side
5. Join Copy to original
6. Blend from shapes where neccessary

This is quite a lengthy process, so any improvement would be appreciated

**Comment by przemir** [comment]
I don't see a reliable way to transfer animation data block for shape keys from one object to another (I expected something similar to CTRL-L and choosing Animation Data, but I didn't found such option). Method to copy driver won't work as well because it requires mouse position to identify value widget. And rewriting drivers by hand in script seems risky: blender may add new variable with new version and my script won't handle this and lose this information silently.
I added warning if object contains animation data block (drivers, keyframed values etc.) connected with shape keys to make sure user is aware of loosing those data. Other than that I can't do much more to preserve drivers connected to shape keys.
